# Generated by Django 3.2.9 on 2022-01-25 16:32

import core.utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="image",
            field=models.ImageField(
                null=True, upload_to=core.utils.models.file_upload_path
            ),
        ),
        migrations.CreateModel(
            name="TopicLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Last modified date"),
                ),
                ("url", models.URLField()),
                (
                    "url_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("AUDIO", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="topic.topic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
