# Generated by Django 3.2.9 on 2022-01-25 02:45

import core.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Last modified date"),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=250)),
                (
                    "image",
                    models.ImageField(upload_to=core.utils.models.file_upload_path),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
