# Generated by Django 3.2.9 on 2022-01-25 16:32

import core.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="image",
            field=models.ImageField(
                null=True, upload_to=core.utils.models.file_upload_path
            ),
        ),
    ]
