# Generated by Django 3.2.9 on 2022-02-12 19:28

import core.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sobrenome"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        default="default/user-photo.png",
                        upload_to=core.utils.models.file_upload_path,
                        verbose_name="Foto",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14, null=True, unique=True, verbose_name="CPF"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(null=True, verbose_name="Data de nascimento"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de cadastro"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="Último login"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Usuário ativo"),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="Usuário admin"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
